Add tag iframe to contact form
LibreSign/site pull request #19
Opened 2023-12-26 15:45 UTC by Any97Cris

Task is not complete. It remains to check the possibility of CRM.

2023-12-26 21:26 UTC, vitormattos commented
Current status:

Form Before


![Image](https://github.com/LibreSign/libresign-www/assets/54338576/8d1cd406-77a3-48cc-b0b4-1bf53bcdd5f1)

Form After


![Image](https://github.com/LibreSign/libresign-www/assets/54338576/128679ea-11fc-493b-931d-27592a671afc)

2023-12-26 21:26 UTC, vitormattos commented
Close #13

2023-12-27 22:12 UTC, giovannism20 commented
Thank u @vitormattos for the print, it's helpful for the code review. About the style: your intention is to make style like the old form and we need to remember that the texts needs to be in english.

2023-12-27 22:36 UTC, vitormattos commented
We have three possible ways now:

1. Maintain as we can se now, using iframe. By this way will be necessary only do small changes at LimeSurvey side and create a specific template to LibreSign contact form
2. Implement the form direct by JS sending a post to LimeSurvey. I dislike this approach a bit because if we change the form from LimeSurvey side, will break the contact form
3. Pair with @DaianeAlvesRJ to create a form from SuiteCRM side and do the same what we made using LimeSurvey checking how to embed the generated form from SuiteCRM at point of contact form of this PR.

We need to think what will be more easy and best for now.

Using SuiteCRM would be good because the contact will turn to be a contact inside our CRM and sounds as a good idea.

2023-12-27 23:02 UTC, giovannism20 commented
I like the option 1 and 3

2023-12-28 16:12 UTC, vitormattos commented
Form generated by SuiteCRM:

```html
<form id="WebToLeadForm" action="https://crm.librecode.coop/index.php?entryPoint=WebToPersonCapture" method="POST" name="WebToLeadForm">
<input name="last_name" id="last_name" type="text" required="" />
<input name="email1" id="email1" type="email" />
<input name="phone_mobile" id="phone_mobile" type="text" />
<input name="description" id="description" type="text" />
<input name="Submit" type="submit" value="Submit" />
<input name="campaign_id" id="campaign_id" type="hidden" value="91c4e277-95b8-ce28-91fd-658d9aa871ac" />
<input name="redirect_url" id="redirect_url" type="hidden" value="https://libresign.coop/thank-you-contact" />
<input name="assigned_user_id" id="assigned_user_id" type="hidden" value="89cce704-603d-79d7-b069-65660c3a0b7d" />
<input name="moduleDir" id="moduleDir" type="hidden" value="Contacts" />
</form>
```

2023-12-29 14:07 UTC, vitormattos approved these changes

2023-12-29 14:12 UTC, vitormattos requested changes

2023-12-29 14:12 UTC, vitormattos commented on source/thank-you-contact.blade.php
> +  </body>
```suggestion
@endsection
```

2023-12-29 14:12 UTC, vitormattos commented on source/thank-you-contact.blade.php
> +  <body>
Move this to `_layouts.main`
```suggestion
```

2023-12-29 14:17 UTC, vitormattos commented on source/thank-you-contact.blade.php
> +    </header>
Move to `_layout.main`
```suggestion
```

2023-12-29 14:18 UTC, vitormattos commented on source/thank-you-contact.blade.php
> +    </script>
Move to `_layout.main`
```suggestion
```

2023-12-29 16:19 UTC, giovannism20 approved these changes

2023-12-29 19:35 UTC, vitormattos approved these changes

2023-12-29 19:36 UTC, merged