Theme Rebrand
LibreSign/site pull request #4
Opened 2023-12-07 14:40 UTC by giovannism20

This PR includes a lot modifications such as:
- Add the structure to have blog
- Removing unnecessary comments
- Update on composer.json and README.md
- Split some "components"
- Remove unused files

2023-12-09 17:22 UTC, vitormattos requested changes
Small fixes and able to merge and follow making small PR's.

2023-12-09 17:22 UTC, vitormattos commented on source/_layouts/main.blade.php
> +  </head>
```suggestion
  </head>
  <body>
      @yield('body')
  </body>
```

2023-12-09 17:22 UTC, vitormattos commented on source/_layouts/main.blade.php
> +    <title>LibreSign - Electronic signature of digital documents</title>
```suggestion
    <title>{{ $page->title }}</title>
```

2023-12-09 17:22 UTC, vitormattos commented on source/_layouts/main.blade.php
> +<html lang="en">
```suggestion
<html lang="{{ $page->language ?? 'en' }}">
```

2023-12-09 17:22 UTC, vitormattos commented on source/_layouts/main.blade.php
> +    <meta name="description" content="LibreSign - Electronic signature of digital documents">
```suggestion
    <link rel="canonical" href="{{ $page->getUrl() }}">
    <meta name="description" content="{{ $page->description }}">
```

2023-12-09 17:22 UTC, vitormattos commented on source/_layouts/main.blade.php
> +    <link rel="stylesheet" href="assets/css/ud-styles.css" />
```suggestion
    <link rel="stylesheet" href="assets/css/ud-styles.css" />
    <link rel="stylesheet" href="{{ mix('css/main.css', 'assets/build') }}">
    <!-- Primary Meta Tags -->
    <script defer src="{{ mix('js/main.js', 'assets/build') }}"></script>
```

2023-12-09 17:22 UTC, vitormattos commented
DCO disliked your commit.

2023-12-09 17:44 UTC, vitormattos commented on docker-compose.yml
> +      dockerfile: Dockerfile
Only is necessary if the Dockerfile have a name different as `Dockerfile`
```suggestion
```

2023-12-10 20:20 UTC, giovannism20 commented
Hey @vitormattos since do you suggested for make little modifications from this pull request I'll not make more commits here ;)

2023-12-11 00:47 UTC, vitormattos approved these changes

2023-12-11 00:48 UTC, merged